### ISSUE TITLE
Properties of fourier transform

### ISSUE THREAD

**Issue by aglie** [k-eks/ThePictureBookOfFourierTransforms#9]
Scaling

![oscillating_circle](https://user-images.githubusercontent.com/2978725/45361001-5d207280-b5d1-11e8-84f4-15458ccd70e1.gif)
![oscillating_circle_fft](https://user-images.githubusercontent.com/2978725/45361006-614c9000-b5d1-11e8-8616-52ccb1d8b0fe.gif)

**Comment by aglie** [comment]
Rotation

![rocking_square](https://user-images.githubusercontent.com/2978725/45361048-85a86c80-b5d1-11e8-85be-d56cff677db3.gif)
![rocking_square_fft](https://user-images.githubusercontent.com/2978725/45361049-85a86c80-b5d1-11e8-8d29-a6aef2057a98.gif)

**Comment by aglie** [comment]
Inversion

![flipping_triangle](https://user-images.githubusercontent.com/2978725/45361064-9822a600-b5d1-11e8-9a83-821baf3a68ee.gif)
![flipping_triangle_fft](https://user-images.githubusercontent.com/2978725/45361065-9822a600-b5d1-11e8-9ebc-8ad71e228dda.gif)

**Comment by aglie** [comment]
Translation

![moving_rect](https://user-images.githubusercontent.com/2978725/45361115-ab357600-b5d1-11e8-8e0d-b15a13802d6c.gif)
![moving_rect_fft](https://user-images.githubusercontent.com/2978725/45361116-abce0c80-b5d1-11e8-8968-00582358b048.gif)
![moving_point](https://user-images.githubusercontent.com/2978725/45361121-af619380-b5d1-11e8-9fb1-8a683f2babcf.gif)
![moving_point_fft](https://user-images.githubusercontent.com/2978725/45361122-af619380-b5d1-11e8-8e58-5d63c1c35d63.gif)

**Comment by aglie** [comment]
Apologise for the fact that the image and its FFT are in separate gifs and are not exactly synchronised at the moment.

**Comment by k-eks** [comment]
I am a big fan and feel inspired of what is shown but not so much of the how it is shown. I find animations impractical because if they are even the slightest bit out of sync, everything is messed up. Furthermore, they make it harder to compare how the states changes when compared to a frame-by-frame approach where you can directly compare two states and how they have changed instead of looping through the animation over and over again. Also, with an animation you can never really compare to images at once because once you look at one shape by the time you look at the fourier transform, it is already at the next frame.

May I suggest the following:
making a series of regular polygons and scale and rotate them (and some rotations will also represent an inversion) and display them in a more tabulated manner (like with the [Gauss functions](https://github.com/k-eks/ThePictureBookOfFourierTransforms/wiki/Gauss-functions)). I have some code which can make that happen, all I have to do is to do some minor adjustments to the code I used for generating the Guass functions.

What are your thoughts on that?

Single pixels might be a topic on its own, let me think about it a little.

**Comment by aglie** [comment]
Oh, you are right in that putting those things in two different gifs is a
crap idea, but I really like the directness of it.

However, you approach of small multiple figures works amazingly well, so if
you will have a take on the properties it would be amazing. I just had this
gifs ready and decided it would be good to upload them.

вт, 11 сент. 2018 г. в 15:47, Gregor Hofer <notifications@github.com>:

**Comment by k-eks** [comment]
I have put the "classical" crystallographic shapes together. I would be happy about some input, especially about the triangle because I want to mark or note somehow that the first and third as well as second and fourth are inversions to each others.
about non-classical crystallographic shapes, I would have gone with pentagon, octagon and dodecagon because I think these are the important ones for quasi-crystals. Are there more?

![shapes_crys_ft](https://user-images.githubusercontent.com/12133169/45559464-d377db80-b842-11e8-9788-3165b3c6b516.png)
![shapes_crys](https://user-images.githubusercontent.com/12133169/45559466-d4107200-b842-11e8-8aa9-1c9fa8c1341d.png)

**Comment by aglie** [comment]
Oh, these are actually pretty tricky. You see that the FFT of a square at
position 1 and 3 are the same as would be the real fourier transform for a
square. For rotated you see those extra lines appearing (this are wrapping
effects). I do not know what to do about them though, in my gifs those are
present too.

пт, 14 сент. 2018 г. в 17:25, Gregor Hofer <notifications@github.com>:

**Comment by k-eks** [comment]
Maybe some "clever" image cropping? We could simply hide the wrapping effects in simple explanations. What do you think?
by croping this image

![5-gon_rot0 0_ftc](https://user-images.githubusercontent.com/12133169/45747862-616b1200-bc07-11e8-9601-5769027b64bc.png)

to

![5-gon_rot0 0_ftc](https://user-images.githubusercontent.com/12133169/45747916-8cedfc80-bc07-11e8-9236-46e1d438fb14.png)

**Comment by aglie** [comment]
Yep, that works well

ср, 19 сент. 2018 г. в 12:30, Gregor Hofer <notifications@github.com>:

**Comment by k-eks** [comment]
![ft_aperiodic](https://user-images.githubusercontent.com/12133169/45817918-7798d100-bce0-11e8-9bb9-527af8fdba35.png)
![shapes_aperiodic](https://user-images.githubusercontent.com/12133169/45817949-87b0b080-bce0-11e8-96cc-e5d0543eb1ad.png)

![crstalshapes](https://user-images.githubusercontent.com/12133169/45817875-5932d580-bce0-11e8-821b-30d93bd1149a.png)
![ft_crystalshapes](https://user-images.githubusercontent.com/12133169/45817876-59cb6c00-bce0-11e8-91a2-59985b83f59b.png)

**Comment by aglie** [comment]
Brilliant!

чт, 20 сент. 2018 г. в 14:22, Gregor Hofer <notifications@github.com>:

**Comment by k-eks** [comment]
Please, could someone make a fact check on the corresponding wiki page
[https://github.com/k-eks/ThePictureBookOfFourierTransforms/wiki/Regular-polygons](url)
and close this issue if done?
Thanks!

**Comment by aglie** [comment]
Hi @k-eks,

The page is brilliant, though there is a tiny issue with the explanation. The facts you mention are almost correct except for the tiny one here:

> However, the Fourier transform will always contain a center of inversion, which gives rise to Friedel's law in experimental diffraction techniques such as single-crystal X-ray diffraction.

We do have a Friedel's law, but that one is to do with _intensities_ of the scattering, the phases of different arms of non-centrosymmetric polygons are different: one arm would be red-orange-yellow-...-violet going from centre to the outside of the arm, while its inverse will have the opposite change in phases: violet-blue-... going from inside out.

One more fact you could mention is that all even polygons can be thought of as a multiplication of a number of sinc functions, so the fourier transform contains plenty of zeros, while for uneven polygons, they look more like lines, without obvious sinc modulation along the arms.

**Comment by k-eks** [comment]
Thanks and finally done :)
